version: '3.1'
services:
  dairo-nps:
    image: dairopapa/dairo-nps:1.0.0
#    build: .
    restart: always
    container_name: dairo-nps
    network_mode: host

    environment:
      #时区,解决时间不一致的bug
      TZ: Asia/Shanghai

      #解决控制台输出中文乱码
      LANG: C.UTF-8

      #后台管理用户
      ENV NPS_LOGIN_NAME: admin

      #后台管理密码
      ENV NPS_LOGIN_PWD:

      #后台管理端口
      ENV NPS_WEB_PORT: 1780

      #客户端连接TCP端口
      ENV NPS_TCP_PORT: 1781

      #日志类型
      ENV NPS_LOG_TYPE: 2

      #日志级别
      ENV NPS_LOG_LEVEL: error
    volumes:
      - ./data:/app/data
